### ISSUE TITLE
Detectron2 version 0.1.1

### ISSUE THREAD

**Issue by matakahas** [lolipopshock/Detectron2_AL#2]
Thank you for this great project! I was following the instruction to install version 0.1.1 of Detectron2 with the command below, but it threw an error.
`pip install detectron2==0.1.1 \
    -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu100/torch1.4/index.html`

Error message:
ERROR: Could not find a version that satisfies the requirement detectron2==0.1.1
ERROR: No matching distribution found for detectron2==0.1.1

Could you please let me know how to install the correct version, or perhaps another version that is compatible? Thank you for your help!

**Comment by lolipopshock** [comment]
Thanks! I think this command would only work for linux machines - I also need to update them as well. You might want to try the following: 
```
pip install 'git+https://github.com/facebookresearch/detectron2.git@v0.1.1#egg=detectron2' 

```

Please let me know if you have other questions :)

**Comment by matakahas** [comment]
Thank you, I'll try that!
